/**
 * O PDM — o plano de mídia que a Rise entrega todo mês.
 *
 * GERADO por `scripts/gera-pdm.mjs`. NÃO editar à mão: quando chegar um PDM
 * novo, exporte a planilha e rode o script de novo.
 *
 * Fonte: `RISE_PURE-PILATES_PDM_BRANDPERFORMANCE_Q425Q126_11319`.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * BRUTO, LÍQUIDO E O QUE DÁ PARA COMPARAR
 * ────────────────────────────────────────────────────────────────────────────
 * O `liquido` é o que vira mídia dentro da plataforma; o `bruto` é líquido
 * mais a comissão da agência, e é o que sai do caixa. A comissão nunca chega
 * ao Meta, então o número que o Meta reporta como gasto compara com o
 * LÍQUIDO — usar o bruto faria toda campanha parecer 20% abaixo do plano.
 *
 * Cada mês fecha exatamente com o total que a planilha declara. O gerador
 * recusa gravar se não fechar.
 */

export type BlocoDoPdm = 'performance' | 'operacional';
export type PlataformaDoPdm = 'meta' | 'google' | 'outro';

export interface CampanhaPlanejada {
  bloco: BlocoDoPdm;
  veiculo: string;
  plataforma: PlataformaDoPdm;
  campanha: string;
  etapa: string;
  kpi: string;
  localidade: string;
  /** O que vira mídia na plataforma. */
  liquido: number;
  /** Líquido + comissão da agência: o que sai do caixa. */
  bruto: number;
  impressoes: number | null;
  cliques: number | null;
  cpa: number | null;
  agendamentos: number | null;
  cpl: number | null;
  leads: number | null;
}

export interface MesPlanejado {
  /** No formato 'AAAA-MM'. */
  mes: string;
  /** A aba de origem na planilha, para quem for conferir. */
  aba: string;
  /** Os totais como a própria planilha os declara. */
  declarados: {
    liquido: number;
    bruto: number;
    impressoes: number;
    cliques: number;
    agendamentos: number;
    leads: number;
  };
  campanhas: CampanhaPlanejada[];
}

export const PDM: MesPlanejado[] = [
  {
    mes: '2026-04',
    aba: 'ABRIL26',
    declarados: {
      liquido: 214666,
      bruto: 268332.5,
      impressoes: 8856069,
      cliques: 71436,
      agendamentos: 4804,
      leads: 330,
    },
    campanhas: [
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTITUCIONAL",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 42000,
      bruto: 52500,
      impressoes: 93333,
      cliques: 17427,
      cpa: 30,
      agendamentos: 1400,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "PILATES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 30000,
      bruto: 37500,
      impressoes: 214286,
      cliques: 17442,
      cpa: 33,
      agendamentos: 909,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PURE PASS",
      etapa: "Shopping",
      kpi: "Compra",
      localidade: "5km de cada unidade",
      liquido: 30000,
      bruto: 37500,
      impressoes: 1535312,
      cliques: 8357,
      cpa: 270,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "REMARKETING",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 20000,
      bruto: 25000,
      impressoes: 1023541,
      cliques: 5571,
      cpa: 45,
      agendamentos: 444,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PILATES PLAY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 1000,
      bruto: 1250,
      impressoes: 43440,
      cliques: 238,
      cpa: 24,
      agendamentos: 42,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "DCO - TODAS",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 82500,
      bruto: 103125,
      impressoes: 3694581,
      cliques: 19643,
      cpa: 42,
      agendamentos: 1964,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Sacomã 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Sacomã e São Vicente Centro",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São Vicente Centro 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Sacomã e São Vicente Centro",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Taipas 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Sacomã e São Vicente Centro",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São Bernanrdo Do Campo 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Sacomã e São Vicente Centro",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "AQUISIÇÃO LOJA",
      etapa: "Shopping",
      kpi: "Compra",
      localidade: "5km de cada unidade",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: 0,
      cpa: 65,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "BRANDING - THRUPLAY - ATIVAÇÕES",
      etapa: "Streaming",
      kpi: "Videoview",
      localidade: "Cidade das unidades",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: null,
      cpa: null,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "BRANDING - THRUPLAY - MATRIZ",
      etapa: "Streaming",
      kpi: "Videoview",
      localidade: "Cidade das unidades",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: null,
      cpa: null,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "DCO - REMARKETING VIDEOS",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: 0,
      cpa: 60,
      agendamentos: 0,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "YouTube",
      plataforma: 'outro',
      campanha: "BRANDING - VISUALIZAÇÃO - MATRIZ",
      etapa: "Streaming",
      kpi: "Videoview",
      localidade: "Cidade das unidades",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: null,
      cpa: null,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Microsoft Ads",
      plataforma: 'outro',
      campanha: "NETFLIX + PRIME",
      etapa: "Streaming",
      kpi: "Videoview",
      localidade: "",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: null,
      cpa: null,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'operacional',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "FRANQUIAS",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "SC/RS",
      liquido: 0,
      bruto: 0,
      impressoes: null,
      cliques: 0,
      cpa: null,
      agendamentos: null,
      cpl: 140,
      leads: 0,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "RH-INSTRUTOR",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 2000,
      bruto: 2500,
      impressoes: 8400,
      cliques: 673,
      cpa: null,
      agendamentos: null,
      cpl: 17,
      leads: 118,
    },
    {
      bloco: 'operacional',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTRUTORES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 3000,
      bruto: 3750,
      impressoes: 195695,
      cliques: 714,
      cpa: null,
      agendamentos: null,
      cpl: 46,
      leads: 65,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "ACADEMY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 2000,
      bruto: 2500,
      impressoes: 1950480,
      cliques: 855,
      cpa: null,
      agendamentos: null,
      cpl: 13.6,
      leads: 147,
    },
    ],
  },
  {
    mes: '2026-05',
    aba: 'MAIO26',
    declarados: {
      liquido: 248365,
      bruto: 310456.25,
      impressoes: 10008617,
      cliques: 81134,
      agendamentos: 5320,
      leads: 618,
    },
    campanhas: [
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTITUCIONAL",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 42000,
      bruto: 52500,
      impressoes: 93333,
      cliques: 17427,
      cpa: 30,
      agendamentos: 1400,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "PILATES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 35900,
      bruto: 44875,
      impressoes: 256429,
      cliques: 20872,
      cpa: 33,
      agendamentos: 1088,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PURE PASS",
      etapa: "Shopping",
      kpi: "Compra",
      localidade: "5km de cada unidade",
      liquido: 30000,
      bruto: 37500,
      impressoes: 1535312,
      cliques: 8357,
      cpa: 270,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "REMARKETING",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 20000,
      bruto: 25000,
      impressoes: 1023541,
      cliques: 5571,
      cpa: 45,
      agendamentos: 444,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "DCO - TODAS",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 94100,
      bruto: 117625,
      impressoes: 4214062,
      cliques: 22405,
      cpa: 42,
      agendamentos: 2240,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Sacomã 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Sacomã",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São Vicente Centro 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São Vicente Centro",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Taipas 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Taipas",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São Bernanrdo Do Campo 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São Bernanrdo do Campo",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Barra Itaúna Shopping 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Barra Itaúna Shopping",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São João - Guarulhos 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São João - Guarulhos",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Jacareí - Villa Branca 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Jacareí - Villa Branca",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Jacanã 2",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: 0,
      cpa: 49,
      agendamentos: 0,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Quarta Parada Alto da Mooca 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Quarta Parada",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'operacional',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "FRANQUIAS",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "SC/RS",
      liquido: 5000,
      bruto: 6250,
      impressoes: null,
      cliques: 540,
      cpa: null,
      agendamentos: null,
      cpl: 140,
      leads: 36,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "RH-INSTRUTOR",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 1200,
      bruto: 1500,
      impressoes: 8400,
      cliques: 404,
      cpa: null,
      agendamentos: null,
      cpl: 17,
      leads: 71,
    },
    {
      bloco: 'operacional',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTRUTORES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 10000,
      bruto: 12500,
      impressoes: 652316,
      cliques: 2381,
      cpa: null,
      agendamentos: null,
      cpl: 46,
      leads: 217,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PILATES PLAY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 1000,
      bruto: 1250,
      impressoes: 43440,
      cliques: 238,
      cpa: 24,
      agendamentos: 42,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "ACADEMY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 4000,
      bruto: 5000,
      impressoes: 1950480,
      cliques: 1709,
      cpa: null,
      agendamentos: null,
      cpl: 13.6,
      leads: 294,
    },
    ],
  },
  {
    mes: '2026-06',
    aba: 'JUNHO26',
    declarados: {
      liquido: 258529,
      bruto: 323161.25,
      impressoes: 13680868,
      cliques: 74672,
      agendamentos: 5631,
      leads: 618,
    },
    campanhas: [
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTITUCIONAL",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 42000,
      bruto: 52500,
      impressoes: 93333,
      cliques: 17427,
      cpa: 30,
      agendamentos: 1400,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "PILATES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 30900,
      bruto: 38625,
      impressoes: 220714,
      cliques: 17965,
      cpa: 33,
      agendamentos: 936,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PURE PASS",
      etapa: "Shopping",
      kpi: "Compra",
      localidade: "5km de cada unidade",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: 0,
      cpa: 270,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "REMARKETING",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 20000,
      bruto: 25000,
      impressoes: 1023541,
      cliques: 5571,
      cpa: 45,
      agendamentos: 444,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "DCO - TODAS",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 109100,
      bruto: 136375,
      impressoes: 4885804,
      cliques: 25976,
      cpa: 42,
      agendamentos: 2598,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Sacomã 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Sacomã",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São Vicente Centro 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São Vicente Centro",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Taipas 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Taipas",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São Bernanrdo Do Campo 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São Bernanrdo do Campo",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Barra Itaúna Shopping 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Barra Itaúna Shopping",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São João - Guarulhos 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São João - Guarulhos",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Jacareí - Villa Branca 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Jacareí - Villa Branca",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Quarta Parada Alto da Mooca 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Quarta Parada",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "JP Tambaú 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "JP Tambaú",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Arujá Caputera 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Arujá Caputera",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Jacareí Boulevard 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Jacareí Boulevard",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Santo André 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Santo André",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São Gonçalo Alcantara 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São Gonçalo Alcantara",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Galeria Via Della 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Galeria Via Della",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Casa Forte 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Casa Forte",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Sacomã 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Sacomã",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "AWARENESS",
      etapa: "Streaming",
      kpi: "Cliques",
      localidade: "Cidade das unidades",
      liquido: 25000,
      bruto: 31250,
      impressoes: 4340278,
      cliques: null,
      cpa: null,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'operacional',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "FRANQUIAS",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "SC/RS",
      liquido: 5000,
      bruto: 6250,
      impressoes: null,
      cliques: 540,
      cpa: null,
      agendamentos: null,
      cpl: 140,
      leads: 36,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "RH-INSTRUTOR",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 1200,
      bruto: 1500,
      impressoes: 8400,
      cliques: 404,
      cpa: null,
      agendamentos: null,
      cpl: 17,
      leads: 71,
    },
    {
      bloco: 'operacional',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTRUTORES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 10000,
      bruto: 12500,
      impressoes: 652316,
      cliques: 2381,
      cpa: null,
      agendamentos: null,
      cpl: 46,
      leads: 217,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PILATES PLAY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 1000,
      bruto: 1250,
      impressoes: 43440,
      cliques: 238,
      cpa: 24,
      agendamentos: 42,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "ACADEMY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 4000,
      bruto: 5000,
      impressoes: 1950480,
      cliques: 1709,
      cpa: null,
      agendamentos: null,
      cpl: 13.6,
      leads: 294,
    },
    ],
  },
  {
    mes: '2026-07',
    aba: 'JULHO26',
    declarados: {
      liquido: 257863,
      bruto: 322328.75,
      impressoes: 13496719,
      cliques: 75921,
      agendamentos: 5649,
      leads: 613,
    },
    campanhas: [
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTITUCIONAL",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 42000,
      bruto: 52500,
      impressoes: 93333,
      cliques: 17427,
      cpa: 30,
      agendamentos: 1400,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "PILATES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 35000,
      bruto: 43750,
      impressoes: 250000,
      cliques: 20349,
      cpa: 33,
      agendamentos: 1061,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PURE PASS",
      etapa: "Shopping",
      kpi: "Compra",
      localidade: "5km de cada unidade",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: 0,
      cpa: 270,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "REMARKETING",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 20000,
      bruto: 25000,
      impressoes: 1023541,
      cliques: 5571,
      cpa: 45,
      agendamentos: 444,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "DCO - TODAS",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 106500,
      bruto: 133125,
      impressoes: 4769369,
      cliques: 25357,
      cpa: 42,
      agendamentos: 2536,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "INDIQUE PILATES",
      etapa: "Scrolling",
      kpi: "Cliques",
      localidade: "5km de cada unidade",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: 0,
      cpa: null,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Barra Itaúna Shopping 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Barra Itaúna Shopping",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São João - Guarulhos 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São João - Guarulhos",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Jacareí - Villa Branca 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Jacareí - Villa Branca",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Quarta Parada Alto da Mooca 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Quarta Parada",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "JP Tambaú 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "JP Tambaú",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Arujá Caputera 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Arujá Caputera",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Jacareí Boulevard 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Jacareí Boulevard",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Santo André 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Santo André",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São Gonçalo Alcantara 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São Gonçalo Alcantara",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Galeria Via Della 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Galeria Via Della",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Casa Forte 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Casa Forte",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Sacomã 1/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Sacomã",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "AWARENESS",
      etapa: "Streaming",
      kpi: "Cliques",
      localidade: "Cidade das unidades",
      liquido: 25000,
      bruto: 31250,
      impressoes: 4340278,
      cliques: null,
      cpa: null,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "FRANQUIAS",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "SC/RS",
      liquido: 5000,
      bruto: 6250,
      impressoes: null,
      cliques: 540,
      cpa: null,
      agendamentos: null,
      cpl: 140,
      leads: 31,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "RH-INSTRUTOR",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 1200,
      bruto: 1500,
      impressoes: 8400,
      cliques: 404,
      cpa: null,
      agendamentos: null,
      cpl: 17,
      leads: 71,
    },
    {
      bloco: 'operacional',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTRUTORES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 10000,
      bruto: 12500,
      impressoes: 652316,
      cliques: 2381,
      cpa: null,
      agendamentos: null,
      cpl: 46,
      leads: 217,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PILATES PLAY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 1000,
      bruto: 1250,
      impressoes: 43440,
      cliques: 238,
      cpa: 24,
      agendamentos: 42,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "ACADEMY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 4000,
      bruto: 5000,
      impressoes: 1950480,
      cliques: 1709,
      cpa: null,
      agendamentos: null,
      cpl: 13.6,
      leads: 294,
    },
    ],
  },
  {
    mes: '2026-08',
    aba: 'AGOSTO26',
    declarados: {
      liquido: 254864,
      bruto: 318580,
      impressoes: 13578156,
      cliques: 73701,
      agendamentos: 4877,
      leads: 984,
    },
    campanhas: [
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTITUCIONAL",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 42000,
      bruto: 52500,
      impressoes: 93333,
      cliques: 17427,
      cpa: 30,
      agendamentos: 1400,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "PILATES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 35000,
      bruto: 43750,
      impressoes: 250000,
      cliques: 17857,
      cpa: 33,
      agendamentos: 1061,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PURE PASS",
      etapa: "Shopping",
      kpi: "Compra",
      localidade: "5km de cada unidade",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: 0,
      cpa: 270,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "REMARKETING",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 20000,
      bruto: 25000,
      impressoes: 1023541,
      cliques: 5571,
      cpa: 60,
      agendamentos: 333,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "DCO - TODAS",
      etapa: "Scrolling",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 106500,
      bruto: 133125,
      impressoes: 4769369,
      cliques: 25357,
      cpa: 55,
      agendamentos: 1936,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "INDIQUE PILATES",
      etapa: "Scrolling",
      kpi: "Cliques",
      localidade: "5km de cada unidade",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: 0,
      cpa: null,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "JP Tambaú 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "JP Tambaú",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Arujá Caputera 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Arujá Caputera",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Jacareí Boulevard 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Jacareí Boulevard",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Santo André 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Santo André",
      liquido: 666,
      bruto: 832.5,
      impressoes: 29825,
      cliques: 159,
      cpa: 49,
      agendamentos: 14,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "São Gonçalo Alcantara 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "São Gonçalo Alcantara",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Galeria Via Della 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Galeria Via Della",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Casa Forte 3/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Casa Forte",
      liquido: 833,
      bruto: 1041.25,
      impressoes: 37304,
      cliques: 198,
      cpa: 49,
      agendamentos: 17,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "Sacomã 2/3",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "Sacomã",
      liquido: 500,
      bruto: 625,
      impressoes: 22391,
      cliques: 119,
      cpa: 49,
      agendamentos: 10,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'performance',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "AWARENESS",
      etapa: "Streaming",
      kpi: "Cliques",
      localidade: "Cidade das unidades",
      liquido: 25000,
      bruto: 31250,
      impressoes: 4340278,
      cliques: null,
      cpa: null,
      agendamentos: null,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "FRANQUIAS",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "SC/RS",
      liquido: 5000,
      bruto: 6250,
      impressoes: 868056,
      cliques: 540,
      cpa: null,
      agendamentos: null,
      cpl: 140,
      leads: 31,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "RH-INSTRUTOR",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 11200,
      bruto: 14000,
      impressoes: 8400,
      cliques: 3771,
      cpa: null,
      agendamentos: null,
      cpl: 17,
      leads: 659,
    },
    {
      bloco: 'operacional',
      veiculo: "Google Ads",
      plataforma: 'google',
      campanha: "INSTRUTORES",
      etapa: "Searching",
      kpi: "Lead",
      localidade: "Cidade das unidades",
      liquido: 0,
      bruto: 0,
      impressoes: 0,
      cliques: 0,
      cpa: null,
      agendamentos: null,
      cpl: 46,
      leads: 0,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "PILATES PLAY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 1000,
      bruto: 1250,
      impressoes: 43440,
      cliques: 238,
      cpa: 24,
      agendamentos: 42,
      cpl: null,
      leads: null,
    },
    {
      bloco: 'operacional',
      veiculo: "Meta Ads",
      plataforma: 'meta',
      campanha: "ACADEMY",
      etapa: "Shopping",
      kpi: "Lead",
      localidade: "5km de cada unidade",
      liquido: 4000,
      bruto: 5000,
      impressoes: 1950480,
      cliques: 1709,
      cpa: null,
      agendamentos: null,
      cpl: 13.6,
      leads: 294,
    },
    ],
  },
];
