-- Pedidos de uniformes e produtos da Pure Store.
--
-- A equipe da Pure Store monta o pedido do franqueado no Hub (Gerador de
-- pedidos), salva, e acompanha no Gerenciador, que é um quadro de três colunas:
-- realizado -> separado -> entregue. "realizado" é o status de quem nasce.
--
-- Quem mexe: qualquer colaborador (mesma regra de demand_groups). Franqueado
-- não enxerga nada daqui.
--
-- Os totais ficam gravados no pedido, e não só calculados na tela: o preço do
-- produto muda no site, e o pedido antigo precisa continuar mostrando o valor
-- que foi combinado com o cliente.
--
-- Aplicar pelo SQL Editor ou pela Management API. Nunca `supabase db push`:
-- o histórico remoto de migrations está vazio.

CREATE TABLE IF NOT EXISTS public.pure_store_pedidos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Número curto para falar com o cliente ("pedido 37"), separado do id.
  numero integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,

  cliente_nome text NOT NULL CHECK (length(cliente_nome) BETWEEN 1 AND 200),
  cliente_unidade text NOT NULL DEFAULT '' CHECK (length(cliente_unidade) <= 200),
  cliente_telefone text NOT NULL DEFAULT '' CHECK (length(cliente_telefone) <= 40),

  desconto_percentual numeric(5,2) NOT NULL DEFAULT 0 CHECK (desconto_percentual BETWEEN 0 AND 100),
  subtotal numeric(10,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  desconto_valor numeric(10,2) NOT NULL DEFAULT 0 CHECK (desconto_valor >= 0),
  total numeric(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0),

  status text NOT NULL DEFAULT 'realizado' CHECK (status IN ('realizado', 'separado', 'entregue')),

  criado_por uuid NULL REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS pure_store_pedidos_created_at_idx ON public.pure_store_pedidos (created_at DESC);
CREATE INDEX IF NOT EXISTS pure_store_pedidos_status_idx ON public.pure_store_pedidos (status);

DROP TRIGGER IF EXISTS pure_store_pedidos_set_updated_at ON public.pure_store_pedidos;
CREATE TRIGGER pure_store_pedidos_set_updated_at
  BEFORE UPDATE ON public.pure_store_pedidos
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE IF NOT EXISTS public.pure_store_pedido_itens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pedido_id uuid NOT NULL REFERENCES public.pure_store_pedidos(id) ON DELETE CASCADE,

  -- Nome do produto como estava no dia do pedido; o site pode renomear depois.
  produto text NOT NULL CHECK (length(produto) BETWEEN 1 AND 300),
  tamanho text NOT NULL DEFAULT '' CHECK (length(tamanho) <= 20),
  quantidade integer NOT NULL CHECK (quantidade BETWEEN 1 AND 9999),
  valor_unitario numeric(10,2) NOT NULL CHECK (valor_unitario >= 0),
  -- Ordem das linhas na tela e no PDF.
  posicao integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS pure_store_pedido_itens_pedido_idx
  ON public.pure_store_pedido_itens (pedido_id, posicao);

ALTER TABLE public.pure_store_pedidos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pure_store_pedido_itens ENABLE ROW LEVEL SECURITY;

-- Colaborador faz tudo; franqueado não vê nada (nenhuma policy o alcança).
DROP POLICY IF EXISTS "Colaboradores veem os pedidos da Pure Store" ON public.pure_store_pedidos;
CREATE POLICY "Colaboradores veem os pedidos da Pure Store"
  ON public.pure_store_pedidos FOR SELECT USING (public.is_colaborador(auth.uid()));
DROP POLICY IF EXISTS "Colaboradores criam pedidos da Pure Store" ON public.pure_store_pedidos;
CREATE POLICY "Colaboradores criam pedidos da Pure Store"
  ON public.pure_store_pedidos FOR INSERT WITH CHECK (public.is_colaborador(auth.uid()));
DROP POLICY IF EXISTS "Colaboradores editam pedidos da Pure Store" ON public.pure_store_pedidos;
CREATE POLICY "Colaboradores editam pedidos da Pure Store"
  ON public.pure_store_pedidos FOR UPDATE USING (public.is_colaborador(auth.uid()));
DROP POLICY IF EXISTS "Colaboradores excluem pedidos da Pure Store" ON public.pure_store_pedidos;
CREATE POLICY "Colaboradores excluem pedidos da Pure Store"
  ON public.pure_store_pedidos FOR DELETE USING (public.is_colaborador(auth.uid()));

DROP POLICY IF EXISTS "Colaboradores veem os itens dos pedidos" ON public.pure_store_pedido_itens;
CREATE POLICY "Colaboradores veem os itens dos pedidos"
  ON public.pure_store_pedido_itens FOR SELECT USING (public.is_colaborador(auth.uid()));
DROP POLICY IF EXISTS "Colaboradores criam itens dos pedidos" ON public.pure_store_pedido_itens;
CREATE POLICY "Colaboradores criam itens dos pedidos"
  ON public.pure_store_pedido_itens FOR INSERT WITH CHECK (public.is_colaborador(auth.uid()));
DROP POLICY IF EXISTS "Colaboradores editam itens dos pedidos" ON public.pure_store_pedido_itens;
CREATE POLICY "Colaboradores editam itens dos pedidos"
  ON public.pure_store_pedido_itens FOR UPDATE USING (public.is_colaborador(auth.uid()));
DROP POLICY IF EXISTS "Colaboradores excluem itens dos pedidos" ON public.pure_store_pedido_itens;
CREATE POLICY "Colaboradores excluem itens dos pedidos"
  ON public.pure_store_pedido_itens FOR DELETE USING (public.is_colaborador(auth.uid()));

-- O dump da migração de abril não trouxe os GRANTs do schema public.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pure_store_pedidos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.pure_store_pedido_itens TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.pure_store_pedidos_numero_seq TO authenticated;
GRANT ALL ON public.pure_store_pedidos TO service_role;
GRANT ALL ON public.pure_store_pedido_itens TO service_role;

-- Realtime: o quadro do Gerenciador acompanha o que outra pessoa mover.
DO $$
DECLARE
  tabela text;
BEGIN
  FOREACH tabela IN ARRAY ARRAY['pure_store_pedidos', 'pure_store_pedido_itens']
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
      WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = tabela
    ) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', tabela);
    END IF;
  END LOOP;
END $$;
